<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.1.0</modelVersion>
    <parent>
        <groupId>io.github.youngledo</groupId>
        <artifactId>admin-spring</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>admin-spring-security</artifactId>
    <dependencies>
        <dependency><groupId>io.github.vaadinadminstarter</groupId><artifactId>admin-contracts</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-oauth2-client</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-webmvc</artifactId></dependency>
        <dependency><groupId>com.vaadin</groupId><artifactId>vaadin-core</artifactId><version>${vaadin.version}</version></dependency>
        <dependency><groupId>com.vaadin</groupId><artifactId>vaadin-spring</artifactId><version>${vaadin.version}</version></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
    </dependencies>
</project>
