<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.youngledo</groupId>
        <artifactId>vadmin-spring</artifactId>
        <version>0.1.1-SNAPSHOT</version>
    </parent>
    <artifactId>vadmin-spring-boot-starter</artifactId>
    <name>VAdmin Spring Boot Starter</name>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>src/main/frontend/themes</directory>
                <targetPath>META-INF/resources/themes</targetPath>
            </resource>
        </resources>
    </build>
    <dependencies>
        <dependency><groupId>io.github.youngledo</groupId><artifactId>vadmin-spring-security</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.youngledo</groupId><artifactId>vadmin-spring-jpa</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.youngledo</groupId><artifactId>vadmin-spring-boot</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.youngledo</groupId><artifactId>vadmin-spring-flow</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter</artifactId></dependency>
        <dependency><groupId>com.vaadin</groupId><artifactId>vaadin-dev</artifactId><version>${vaadin.version}</version><optional>true</optional></dependency>
        <dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId><scope>runtime</scope></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
    </dependencies>
</project>
