spring:
  application:
    name: standalone-consumer
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/standalone_consumer}
    username: ${DATABASE_USERNAME:standalone_consumer}
    password: ${DATABASE_PASSWORD:standalone_consumer}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
